### ISSUE TITLE
Resolve XGBoost library loading error

### ISSUE THREAD

**Issue by varchanaiyer** [19Naveen/Knowledge_Representation#10]
![image](https://github.com/user-attachments/assets/0a1f02f4-db22-4ac1-8021-30cef870f59b)

Investigate and fix the XGBoost library loading issue. Ensure compatibility with the project environment and provide clear installation instructions in the README.

**Comment by 19Naveen** [comment]
Hi @varchanaiyer,

Thank you for bringing the XGBoost library loading error to our attention. We're working on resolving the issue and are confident that we can provide a fix by the next working day. We'll also update the README with clear installation instructions to ensure compatibility.

Best regards,
@19Naveen
