### ISSUE TITLE
File upload error: UTF-8 codec can't decode byte in CSV file

### ISSUE THREAD

**Issue by SiranjeeviK** [19Naveen/Knowledge_Representation#6]
# File upload error: UTF-8 codec can't decode byte in CSV file

## Description
When attempting to upload a CSV file for Insights Generation, the following error occurs:

This happens despite the file upload appearing successful initially.

## Steps to Reproduce
1. Navigate to the Insights Generation feature
2. Select a CSV file for upload (file name: "Most Streamed Spoti...", size: 1.0MB)
3. Attempt to process the file

## Expected Behavior
The file should be successfully uploaded and processed for insights generation.

## Actual Behavior
The file upload fails with the UTF-8 decoding error.

## Additional Information
- User interface shows conflicting messages: "File uploaded successfully!" followed by the error message
- The error occurs at byte position 2679 in the file

## Possible Causes
- File encoding issues
- Corrupted data in the CSV file
- Potential bug in the file processing code

## Suggested Next Steps
- Check the encoding of the CSV file
- Examine the contents around byte position 2679
- Review the file upload and processing code for proper error handling

## Screenshots
![image](https://github.com/19Naveen/Knowledge_Representation/assets/81350268/35f813f6-318f-498b-8240-da0815ac9d8d)

## Environment
- Feature: Insights Generation
- File type: CSV
- File size: 1.0MB

## Attachments
- This is the .csv file used,
[Most Streamed Spotify Songs 2024.csv](https://github.com/user-attachments/files/16114852/Most.Streamed.Spotify.Songs.2024.csv)

**Comment by SiranjeeviK** [comment]
The attachment is in **iso-8859-1** format. So we need to convert that into **utf-8**, right?

**Comment by 19Naveen** [comment]
Fixed The Bug using Charlet Library and updated the load_csv() 
Reference : b8a2ab31deca0c91c8109bfdd06b4a0893f3bf5c
